"""
MedVision — Seed Firestore with 20 WHO emergency triage protocols.

Based on:
  - WHO Emergency Triage Assessment and Treatment (ETAT), 2nd ed. 2016
  - ATLS (Advanced Trauma Life Support), 10th ed. 2018
  - WHO Pocket Book of Hospital Care for Children, 2013

Run:  python seed_firestore.py
"""

from __future__ import annotations

import asyncio
import os
import sys
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("medvision.seed")

# ── Protocol data ─────────────────────────────────────────────────────────────

PROTOCOLS: list[dict] = [
    {
        "condition": "cardiac_arrest",
        "display_name": "Cardiac Arrest",
        "priority": "immediate",
        "triage_color": "red",
        "steps": [
            "Call emergency services immediately — do not delay CPR.",
            "Ensure scene safety. Put on gloves if available.",
            "Open airway: head-tilt chin-lift maneuver (jaw thrust if trauma suspected).",
            "Check for normal breathing for no more than 10 seconds.",
            "Begin chest compressions: 30 compressions at rate 100–120/min, depth 5–6 cm.",
            "Give 2 rescue breaths after every 30 compressions (30:2 ratio).",
            "Attach AED as soon as available; follow voice prompts without pausing CPR.",
            "Continue CPR until advanced help arrives or patient shows signs of life.",
        ],
        "visual_signs": [
            "Unresponsive to voice and tap",
            "No visible chest rise or breathing",
            "Absent or gasping respirations (agonal breathing)",
            "Cyanosis (blue lips or fingertips)",
        ],
        "do_not_do": [
            "Do NOT delay CPR to find AED — start compressions immediately.",
            "Do NOT stop for more than 10 seconds.",
            "Do NOT hyperventilate — 1 breath every 6 seconds.",
        ],
        "when_to_call_ems": "Call EMS before starting CPR or simultaneously.",
        "protocol_reference": "WHO ETAT 2016 Ch.2 — Emergency Signs; AHA BLS Guidelines 2020",
        "keywords": ["cardiac_arrest", "no_pulse", "cpr", "heart_stopped", "unconscious", "no_breathing", "aha", "resuscitation"],
    },
    {
        "condition": "severe_bleeding",
        "display_name": "Severe External Bleeding",
        "priority": "immediate",
        "triage_color": "red",
        "steps": [
            "Call EMS immediately.",
            "Apply firm direct pressure with a clean cloth or dressing.",
            "If available, apply a tourniquet 5–7 cm above the wound on a limb (note time applied).",
            "Maintain constant firm pressure — do NOT lift to check until 10 minutes have elapsed.",
            "If blood soaks through, add more dressing on top — do NOT remove original.",
            "Elevate injured limb above heart level if no fracture suspected.",
            "Keep patient lying flat; cover with blanket to prevent shock.",
            "Monitor breathing and pulse every 2 minutes.",
        ],
        "visual_signs": [
            "Rapid pulsating blood flow from wound",
            "Pooling blood on ground or clothing saturated",
            "Pale, cold, clammy skin",
            "Altered consciousness indicating haemorrhagic shock",
        ],
        "do_not_do": [
            "Do NOT apply tourniquet to neck, chest, or abdomen.",
            "Do NOT remove embedded objects — stabilise in place.",
            "Do NOT give food or water (risk of surgery).",
        ],
        "when_to_call_ems": "Immediately — uncontrolled haemorrhage is life-threatening within minutes.",
        "protocol_reference": "ATLS 10th ed. 2018 Ch.3 — Haemorrhage Control; WHO ETAT 2016 Sec.2",
        "keywords": ["bleeding", "haemorrhage", "hemorrhage", "blood_loss", "tourniquet", "wound", "laceration"],
    },
    {
        "condition": "choking",
        "display_name": "Choking (Airway Obstruction)",
        "priority": "immediate",
        "triage_color": "red",
        "steps": [
            "Ask 'Are you choking?' — if patient cannot speak, cough, or breathe, act immediately.",
            "Call EMS if patient deteriorates or loses consciousness.",
            "Perform 5 firm back blows between shoulder blades with heel of hand.",
            "Follow with 5 abdominal thrusts (Heimlich): stand behind, hands above navel below xiphoid.",
            "Alternate 5 back blows and 5 abdominal thrusts until obstruction clears.",
            "If patient is pregnant or obese, use chest thrusts instead of abdominal thrusts.",
            "If patient loses consciousness, lower to ground and begin CPR — each time you open airway look for object and remove if visible.",
            "For infant < 1 year: 5 back blows + 5 chest thrusts (not abdominal).",
        ],
        "visual_signs": [
            "Universal choking sign (hands clutching throat)",
            "Inability to speak or cry",
            "High-pitched stridor or no breath sounds",
            "Cyanosis developing rapidly",
        ],
        "do_not_do": [
            "Do NOT perform blind finger sweeps in airway.",
            "Do NOT perform abdominal thrusts on infants under 1 year.",
            "Do NOT slap back if patient can still cough effectively.",
        ],
        "when_to_call_ems": "Immediately if object does not dislodge after first cycle or patient loses consciousness.",
        "protocol_reference": "WHO ETAT 2016 Airway Management; AHA BLS Choking Algorithm 2020",
        "keywords": ["choking", "airway_obstruction", "heimlich", "foreign_body", "can't_breathe", "stridor"],
    },
    {
        "condition": "anaphylaxis",
        "display_name": "Anaphylaxis (Severe Allergic Reaction)",
        "priority": "immediate",
        "triage_color": "red",
        "steps": [
            "Call EMS immediately.",
            "Administer epinephrine (adrenaline) 0.3–0.5 mg IM into outer mid-thigh (adults); 0.01 mg/kg for children (max 0.5 mg).",
            "Position patient lying flat with legs elevated; do NOT allow sitting up.",
            "If breathing difficulty, allow sitting up while keeping legs elevated.",
            "Repeat epinephrine every 5–15 minutes if no improvement.",
            "Give supplemental oxygen if available (10–15 L/min via non-rebreather mask).",
            "If unconscious and not breathing, begin CPR.",
            "Monitor blood pressure, pulse, and breathing continuously.",
        ],
        "visual_signs": [
            "Hives (urticaria) or generalised erythema",
            "Angioedema: swelling of lips, tongue, throat",
            "Stridor or wheeze indicating airway compromise",
            "Hypotension and tachycardia (pale, weak pulse)",
        ],
        "do_not_do": [
            "Do NOT allow patient to stand or walk — hypotension risk.",
            "Do NOT delay epinephrine for antihistamines — not sufficient alone.",
            "Do NOT use oral medications if airway is compromised.",
        ],
        "when_to_call_ems": "Immediately — anaphylaxis progresses to cardiac arrest within minutes without epinephrine.",
        "protocol_reference": "WHO ETAT 2016 Sec.2 Anaphylaxis; WAO Anaphylaxis Guidelines 2020",
        "keywords": ["anaphylaxis", "allergic_reaction", "epipen", "epinephrine", "bee_sting", "food_allergy", "hives", "swelling"],
    },
    {
        "condition": "stroke",
        "display_name": "Stroke (FAST Protocol)",
        "priority": "immediate",
        "triage_color": "red",
        "steps": [
            "Perform FAST assessment: Face drooping, Arm weakness, Speech slurred, Time to call EMS.",
            "Call EMS immediately — note exact time symptoms began (crucial for thrombolysis decision).",
            "Keep patient calm and still; do NOT give food, water, or medications by mouth.",
            "Position patient: head elevated 30° if conscious; recovery position if unconscious.",
            "Do NOT give aspirin without medical confirmation (haemorrhagic stroke contraindication).",
            "Loosen tight clothing around neck.",
            "Monitor and document neurological status every 5 minutes.",
            "If seizure occurs, protect from injury but do NOT restrain.",
        ],
        "visual_signs": [
            "Sudden facial droop on one side",
            "One arm drifts down when both raised",
            "Slurred or absent speech",
            "Sudden severe headache, vision loss, or ataxia",
        ],
        "do_not_do": [
            "Do NOT give aspirin without ruling out haemorrhagic stroke.",
            "Do NOT allow patient to drive themselves.",
            "Do NOT delay EMS call to 'see if symptoms resolve'.",
        ],
        "when_to_call_ems": "Immediately — thrombolysis window is 3–4.5 hours from symptom onset.",
        "protocol_reference": "WHO Stroke Guidelines 2016; AHA/ASA Acute Stroke Guidelines 2019",
        "keywords": ["stroke", "cva", "brain_attack", "facial_droop", "weakness", "speech", "fast_protocol"],
    },
    {
        "condition": "head_injury",
        "display_name": "Severe Head Injury",
        "priority": "immediate",
        "triage_color": "red",
        "steps": [
            "Call EMS immediately.",
            "Assume spinal injury — immobilise cervical spine with manual in-line stabilisation.",
            "Open airway using jaw-thrust maneuver only (not head-tilt).",
            "Place unconscious breathing patient in recovery position while maintaining spinal alignment.",
            "Control any scalp bleeding with firm pressure (do NOT press on depressed skull fracture).",
            "Monitor GCS (Glasgow Coma Scale) every 5 minutes.",
            "Do NOT remove helmets unless airway is compromised.",
            "Note and report: mechanism of injury, loss of consciousness duration, seizure activity.",
        ],
        "visual_signs": [
            "Altered consciousness or GCS < 14",
            "Clear fluid from nose or ears (CSF leak — basilar skull fracture)",
            "Battle's sign (bruising behind ear) or raccoon eyes",
            "Unequal or unreactive pupils",
        ],
        "do_not_do": [
            "Do NOT remove penetrating objects from skull.",
            "Do NOT administer non-prescribed medications.",
            "Do NOT perform head-tilt if spinal injury suspected.",
        ],
        "when_to_call_ems": "Immediately for any loss of consciousness, GCS < 15, or neurological signs.",
        "protocol_reference": "ATLS 10th ed. 2018 Ch.6 Head Trauma; WHO ETAT 2016 Sec.3",
        "keywords": ["head_injury", "skull_fracture", "concussion", "tbi", "traumatic_brain", "unconscious", "gcs"],
    },
    {
        "condition": "burns",
        "display_name": "Burns (Thermal Injury)",
        "priority": "urgent",
        "triage_color": "yellow",
        "steps": [
            "Ensure scene safety — remove from heat source without endangering rescuer.",
            "Call EMS for burns > 10% body surface area, face/airway involvement, or full-thickness burns.",
            "Cool burn with cool (not cold/iced) running water for 20 minutes within 3 hours of injury.",
            "Remove jewellery and loose clothing from burned area — do NOT remove if stuck.",
            "Cover with clean non-fluffy material (cling film applied loosely lengthwise or sterile dressing).",
            "Keep patient warm — burns cause rapid hypothermia.",
            "Do NOT apply ice, butter, toothpaste, or home remedies.",
            "For airway burns (facial soot, singed nasal hairs, hoarse voice), give oxygen immediately and prepare for rapid deterioration.",
        ],
        "visual_signs": [
            "Superficial: red, painful, dry skin",
            "Partial thickness: blistering, moist, very painful",
            "Full thickness: white/charred, painless, leathery",
            "Facial burns with singed eyebrows/nasal hair suggest inhalation injury",
        ],
        "do_not_do": [
            "Do NOT apply ice — causes vasoconstriction and deepens injury.",
            "Do NOT burst blisters.",
            "Do NOT use adhesive dressings directly on the burn.",
        ],
        "when_to_call_ems": "Burns > 10% BSA adults, > 5% BSA children, all full-thickness, or face/airway burns.",
        "protocol_reference": "WHO Burns Manual 2014; ISBI Practice Guidelines 2016",
        "keywords": ["burns", "thermal_injury", "scalding", "fire", "smoke_inhalation", "skin_burn"],
    },
    {
        "condition": "fractures",
        "display_name": "Suspected Fracture",
        "priority": "urgent",
        "triage_color": "yellow",
        "steps": [
            "Call EMS if open fracture, femur fracture, pelvic fracture, or spinal fracture suspected.",
            "Immobilise the injured limb in the position found using splints, improvised padding.",
            "For open fractures: cover wound with clean moist dressing — do NOT push bone back.",
            "Apply ice pack wrapped in cloth for 20 minutes to reduce swelling.",
            "Check circulation distal to fracture: pulse, sensation, warmth, capillary refill.",
            "Maintain immobilisation and elevate if possible.",
            "Monitor for signs of compartment syndrome: pain out of proportion, paraesthesia, pallor.",
            "Document and report mechanism of injury and neurovascular status.",
        ],
        "visual_signs": [
            "Deformity, angulation, or shortening of limb",
            "Swelling, bruising, crepitus at site",
            "Open wound with bone visible (open fracture)",
            "Inability to weight-bear or reduced range of motion",
        ],
        "do_not_do": [
            "Do NOT attempt to realign fractures in the field.",
            "Do NOT apply tourniquet for closed fractures.",
            "Do NOT ignore neurovascular status distal to fracture.",
        ],
        "when_to_call_ems": "Immediately for femur, pelvis, spine fractures, open fractures, or neurovascular compromise.",
        "protocol_reference": "ATLS 10th ed. 2018 Ch.7; WHO Surgical Care at District Hospital 2003",
        "keywords": ["fracture", "broken_bone", "dislocation", "orthopaedic", "splint", "compartment_syndrome"],
    },
    {
        "condition": "diabetic_emergency",
        "display_name": "Diabetic Emergency (Hypoglycaemia / DKA)",
        "priority": "urgent",
        "triage_color": "yellow",
        "steps": [
            "Call EMS if patient is unconscious or cannot swallow.",
            "If conscious and able to swallow: give 15–20g fast-acting glucose (sugar water, juice, glucose tablets).",
            "Recheck blood glucose after 15 minutes; repeat if still < 4 mmol/L (72 mg/dL).",
            "If unconscious: do NOT give anything by mouth — position in recovery position.",
            "If glucagon kit available and trained: administer IM glucagon 1mg adults, 0.5mg children < 25kg.",
            "For suspected DKA (fruity breath, deep rapid breathing, confusion): give IV fluids only if trained; transport urgently.",
            "Monitor conscious level, blood glucose, and vital signs every 5 minutes.",
            "After recovery, give a complex carbohydrate snack.",
        ],
        "visual_signs": [
            "Hypoglycaemia: trembling, sweating, pallor, confusion, aggression",
            "DKA: Kussmaul breathing (deep rapid sighing), fruity breath, dry mucous membranes",
            "Altered consciousness or combative behaviour in known diabetic",
            "Medical alert bracelet or insulin in patient's belongings",
        ],
        "do_not_do": [
            "Do NOT give oral glucose to unconscious patient.",
            "Do NOT withhold glucose if unsure whether hypo or DKA — hypoglycaemia is immediately life-threatening.",
            "Do NOT leave patient alone after hypoglycaemic episode.",
        ],
        "when_to_call_ems": "Unconsciousness, no response to oral glucose, suspected DKA, or first presentation.",
        "protocol_reference": "WHO ETAT 2016 Hypoglycaemia Management; IDF Clinical Practice Guidelines 2021",
        "keywords": ["hypoglycaemia", "hypoglycemia", "diabetes", "diabetic", "dka", "low_blood_sugar", "insulin", "glucose"],
    },
    {
        "condition": "seizure",
        "display_name": "Seizure / Convulsion",
        "priority": "urgent",
        "triage_color": "yellow",
        "steps": [
            "Call EMS if seizure > 5 minutes, recurrent seizures, or patient does not regain consciousness.",
            "Time the seizure from onset.",
            "Protect from injury: clear surroundings, cushion head with soft material.",
            "Turn patient on their side (recovery position) to prevent aspiration.",
            "Loosen tight clothing around neck.",
            "Do NOT restrain patient or insert anything in mouth.",
            "After seizure ends (postictal phase): monitor breathing and place in recovery position.",
            "Note seizure type, duration, and any preceding events for EMS handover.",
        ],
        "visual_signs": [
            "Tonic-clonic movements of limbs",
            "Upward eye deviation or blinking",
            "Cyanosis during ictal phase",
            "Tongue biting, urinary incontinence",
        ],
        "do_not_do": [
            "Do NOT put anything in the patient's mouth — broken teeth and rescuer injury risk.",
            "Do NOT restrain convulsing limbs — fracture risk.",
            "Do NOT leave patient unattended post-ictally.",
        ],
        "when_to_call_ems": "Duration > 5 minutes (status epilepticus), first seizure, pregnant, or no recovery of consciousness.",
        "protocol_reference": "WHO ETAT 2016 Convulsions Management; Epilepsy Foundation First Aid Guidelines 2017",
        "keywords": ["seizure", "convulsion", "epilepsy", "fit", "status_epilepticus", "shaking"],
    },
    {
        "condition": "drowning",
        "display_name": "Drowning (Near-Drowning)",
        "priority": "immediate",
        "triage_color": "red",
        "steps": [
            "Ensure rescuer safety — do NOT enter water without flotation device.",
            "Call EMS immediately.",
            "Remove the victim from water without delay.",
            "If no breathing: begin CPR immediately — 5 initial rescue breaths then 30:2.",
            "Do NOT attempt to clear water from lungs — this is ineffective and delays CPR.",
            "If AED available, use — do NOT delay due to wet surface (dry chest first briefly).",
            "Keep patient warm and dry — hypothermia develops rapidly.",
            "Transport all drowning victims to hospital even if they appear recovered (secondary drowning risk).",
        ],
        "visual_signs": [
            "Pale or blue skin, lips, fingertips",
            "Absence of breathing and pulse",
            "Wet clothing, water in airway",
            "Altered consciousness or confusion after rescue",
        ],
        "do_not_do": [
            "Do NOT perform Heimlich/abdominal thrusts to remove water — ineffective and harmful.",
            "Do NOT leave recovered patient — secondary drowning can occur 1–24 hours later.",
            "Do NOT delay CPR to assess spinal injury unless obvious trauma mechanism.",
        ],
        "when_to_call_ems": "Every drowning incident, even if patient appears recovered.",
        "protocol_reference": "WHO ETAT 2016; ERC Drowning Guidelines 2021; Szpilman et al. NEJM 2012",
        "keywords": ["drowning", "near_drowning", "submersion", "water_rescue", "secondary_drowning"],
    },
    {
        "condition": "poisoning",
        "display_name": "Poisoning / Toxic Ingestion",
        "priority": "urgent",
        "triage_color": "yellow",
        "steps": [
            "Call EMS and local Poison Control Centre immediately.",
            "Identify the poison if safe to do so: drug name, quantity, time of ingestion.",
            "Do NOT induce vomiting unless specifically directed by Poison Control.",
            "Do NOT give milk, eggs, or home antidotes without medical direction.",
            "If patient is unconscious and breathing: recovery position; airway monitoring.",
            "If pesticide/organophosphate: remove contaminated clothing, wash skin with water, avoid contact.",
            "Bring medication containers, plants, or other evidence to emergency team.",
            "Monitor vital signs, pupil size, and level of consciousness continuously.",
        ],
        "visual_signs": [
            "Miosis (pinpoint pupils): opioids, organophosphates",
            "Mydriasis (dilated pupils): stimulants, anticholinergics",
            "Seizures, hypersalivation, sweating (cholinergic toxidrome)",
            "Altered consciousness, arrhythmia, or metabolic acidosis signs",
        ],
        "do_not_do": [
            "Do NOT induce vomiting for strong acids, alkalis, or petroleum products.",
            "Do NOT give activated charcoal without medical supervision.",
            "Do NOT leave patient unattended.",
        ],
        "when_to_call_ems": "Immediately for all intentional poisonings or any altered consciousness.",
        "protocol_reference": "WHO Model Formulary 2010 Poisoning; Goldfrank's Toxicological Emergencies 10th ed.",
        "keywords": ["poisoning", "overdose", "toxic", "ingestion", "pesticide", "organophosphate", "drug_overdose"],
    },
    {
        "condition": "heat_stroke",
        "display_name": "Heat Stroke",
        "priority": "immediate",
        "triage_color": "red",
        "steps": [
            "Call EMS immediately — heat stroke is rapidly fatal.",
            "Move to cool environment: shade, air conditioning, or any cooler area.",
            "Begin aggressive cooling immediately: immerse in cold water or apply ice packs to neck, axillae, and groin.",
            "Fan the patient while spraying tepid water (evaporative cooling).",
            "Remove all clothing except undergarments.",
            "Give cool (not iced) water to swallow only if fully conscious.",
            "Do NOT give aspirin or paracetamol — they are ineffective for exertional hyperthermia.",
            "Continue cooling until temperature reaches 39°C or EMS arrives.",
        ],
        "visual_signs": [
            "Core temperature > 40°C",
            "Hot, dry skin (classic) or heavy sweating (exertional)",
            "Confusion, combativeness, or altered consciousness",
            "Rapid, strong pulse",
        ],
        "do_not_do": [
            "Do NOT give antipyretics.",
            "Do NOT rub with alcohol.",
            "Do NOT leave patient in vehicle or enclosed hot space.",
        ],
        "when_to_call_ems": "Immediately — cooling must begin in parallel with EMS activation.",
        "protocol_reference": "WHO Environmental Health Criteria 2009; Bouchama & Knochel NEJM 2002",
        "keywords": ["heat_stroke", "hyperthermia", "heat_exhaustion", "exertional_heat", "sunstroke"],
    },
    {
        "condition": "hypothermia",
        "display_name": "Hypothermia",
        "priority": "urgent",
        "triage_color": "yellow",
        "steps": [
            "Call EMS — severe hypothermia (core temp < 30°C) is life-threatening.",
            "Remove from cold environment gently — avoid rough handling (can precipitate arrhythmia).",
            "Remove wet clothing carefully while protecting from wind.",
            "Rewarm passively: insulate with dry blankets, cover head, use vapour-barrier if available.",
            "Provide warm, sweet drinks ONLY if patient is fully conscious and can swallow.",
            "Apply warm compresses to neck, axillae, and groin (not hot — avoid burns).",
            "If unconscious and no pulse: begin CPR; hypothermic hearts may respond to prolonged resuscitation.",
            "Do NOT rub extremities — causes peripheral vasodilation and core cooling.",
        ],
        "visual_signs": [
            "Shivering (mild); absence of shivering (severe — ominous sign)",
            "Pale, blue or grey skin",
            "Confusion, slurred speech, ataxia at moderate stages",
            "Bradycardia, hypotension, fixed dilated pupils in severe cases",
        ],
        "do_not_do": [
            "Do NOT rub or massage extremities.",
            "Do NOT apply direct heat sources (hot water, heating pad directly on skin).",
            "Do NOT assume patient is dead until 'warm and dead'.",
        ],
        "when_to_call_ems": "All cases of suspected severe hypothermia (temperature < 32°C or unconscious).",
        "protocol_reference": "ERC Hypothermia Guidelines 2021; Paal et al. Scand J Trauma 2016",
        "keywords": ["hypothermia", "cold_exposure", "frostbite", "freezing", "winter_emergency"],
    },
    {
        "condition": "chest_pain",
        "display_name": "Acute Chest Pain (Suspected ACS)",
        "priority": "immediate",
        "triage_color": "red",
        "steps": [
            "Call EMS immediately — treat all acute chest pain as cardiac until proven otherwise.",
            "Have patient stop all activity and rest in most comfortable position (usually sitting up).",
            "If patient is not allergic and not anticoagulated: give 300mg aspirin to chew (adults only).",
            "Administer oxygen if available for SpO2 < 94% (do NOT routinely oxygen-saturate).",
            "Loosen tight clothing.",
            "Be prepared to perform CPR if patient deteriorates.",
            "Do NOT leave the patient unattended.",
            "Document: onset, character, radiation, associated symptoms (diaphoresis, nausea, dyspnoea).",
        ],
        "visual_signs": [
            "Clutching chest or radiation to left arm/jaw",
            "Diaphoresis (cold sweat)",
            "Pallor, nausea, or vomiting",
            "Shortness of breath",
        ],
        "do_not_do": [
            "Do NOT give nitroglycerin without knowing BP and medical history.",
            "Do NOT allow patient to walk — myocardial oxygen demand.",
            "Do NOT delay EMS call to 'wait and see'.",
        ],
        "when_to_call_ems": "Immediately for all acute chest pain without obvious benign cause.",
        "protocol_reference": "WHO CVD Guidelines 2016; ESC STEMI Guidelines 2018",
        "keywords": ["chest_pain", "heart_attack", "acs", "myocardial_infarction", "mi", "stemi", "angina"],
    },
    {
        "condition": "difficulty_breathing",
        "display_name": "Acute Respiratory Distress",
        "priority": "immediate",
        "triage_color": "red",
        "steps": [
            "Call EMS immediately.",
            "Position patient upright (sitting forward, tripod position) — do NOT lay flat.",
            "Ensure airway is clear; look for foreign bodies or secretions.",
            "Give supplemental oxygen if available: 10–15 L/min via non-rebreather.",
            "For known asthma: assist with prescribed bronchodilator inhaler (salbutamol).",
            "Loosen tight clothing around chest and neck.",
            "Monitor respiratory rate, SpO2 if available, and level of consciousness.",
            "Be prepared to initiate CPR if breathing stops.",
        ],
        "visual_signs": [
            "Respiratory rate > 30/min or < 10/min",
            "Use of accessory muscles (neck, intercostal retractions)",
            "Cyanosis of lips or fingertips",
            "Unable to complete full sentences",
        ],
        "do_not_do": [
            "Do NOT position patient lying flat — worsens most respiratory conditions.",
            "Do NOT over-sedate.",
            "Do NOT give high-flow O2 to known severe COPD without monitoring (hypercapnic risk).",
        ],
        "when_to_call_ems": "Any difficulty breathing that does not immediately resolve with position change.",
        "protocol_reference": "WHO ETAT 2016 Respiratory Signs; BTS Emergency O2 Guidelines 2017",
        "keywords": ["difficulty_breathing", "dyspnoea", "respiratory_distress", "asthma", "copd", "breathless"],
    },
    {
        "condition": "unconscious_patient",
        "display_name": "Unconscious Patient",
        "priority": "immediate",
        "triage_color": "red",
        "steps": [
            "Call EMS immediately.",
            "Ensure scene safety.",
            "Check responsiveness: shout patient's name, tap shoulders firmly.",
            "Open airway: head-tilt chin-lift (jaw-thrust if trauma).",
            "Check for breathing: look for chest rise, listen and feel for 10 seconds.",
            "If not breathing: begin CPR immediately (30 compressions : 2 breaths).",
            "If breathing: place in recovery position (lateral recumbent).",
            "Do NOT leave unattended — re-assess every 2 minutes.",
        ],
        "visual_signs": [
            "Unresponsive to voice and physical stimulus",
            "Absent or abnormal breathing pattern",
            "Pale, grey, or cyanotic complexion",
            "Pupils fixed or unequal",
        ],
        "do_not_do": [
            "Do NOT give oral fluids.",
            "Do NOT leave patient supine if breathing — aspiration risk.",
            "Do NOT delay CPR to assess cause.",
        ],
        "when_to_call_ems": "Immediately — all unconscious patients require advanced care.",
        "protocol_reference": "WHO ETAT 2016 Ch.2; ILCOR BLS 2020",
        "keywords": ["unconscious", "unresponsive", "coma", "collapse", "found_down"],
    },
    {
        "condition": "eye_injury",
        "display_name": "Eye Injury",
        "priority": "urgent",
        "triage_color": "yellow",
        "steps": [
            "Call EMS or arrange urgent ophthalmology referral.",
            "Do NOT rub or apply pressure to the eye.",
            "For chemical exposure: irrigate IMMEDIATELY with copious clean water for 20 minutes.",
            "For penetrating objects: shield but do NOT remove the object.",
            "For blunt trauma: apply cold compress gently around (not on) eye.",
            "Cover injured eye loosely with eye shield or cup — do NOT use fluffy materials.",
            "Cover non-injured eye too (sympathetic movement worsens penetrating injuries).",
            "Document visual acuity: can patient see hand movements, count fingers, detect light?",
        ],
        "visual_signs": [
            "Visible foreign body or protruding object",
            "Hyphema (blood in anterior chamber)",
            "Corneal clouding or laceration",
            "Severe pain, photophobia, or vision change",
        ],
        "do_not_do": [
            "Do NOT remove penetrating foreign bodies.",
            "Do NOT patch an eye with chemical burns — prolongs contact.",
            "Do NOT apply pressure bandages to penetrating eye injuries.",
        ],
        "when_to_call_ems": "Chemical exposure, penetrating injury, sudden vision loss, hyphema.",
        "protocol_reference": "WHO Prevention of Blindness Programme; ATLS 10th ed. Ocular Trauma",
        "keywords": ["eye_injury", "ocular_trauma", "chemical_eye", "foreign_body_eye", "corneal", "hyphema"],
    },
    {
        "condition": "snake_bite",
        "display_name": "Snakebite",
        "priority": "urgent",
        "triage_color": "yellow",
        "steps": [
            "Call EMS and transport to nearest hospital with antivenom urgently.",
            "Keep patient still — movement increases venom absorption.",
            "Immobilise bitten limb at or below heart level with a splint.",
            "Remove jewellery and tight clothing from affected limb.",
            "Apply a crepe bandage pressure immobilisation ONLY for neurotoxic snakes (confirmed — not cytotoxic).",
            "Mark the margin of advancing swelling/bruising with time every 15 minutes.",
            "Do NOT cut, suck, or apply tourniquet to bite site.",
            "Note snake description (colour, markings, head shape) for antivenom selection.",
        ],
        "visual_signs": [
            "Two fang puncture marks at bite site",
            "Progressive local swelling and bruising",
            "Ptosis, diplopia, dysarthria (neurotoxic envenomation)",
            "Haemorrhage from bite, gums, or IV sites (haemotoxic)",
        ],
        "do_not_do": [
            "Do NOT incise, suck, or apply potassium permanganate to bite.",
            "Do NOT apply tourniquet (causes tissue necrosis).",
            "Do NOT give alcohol.",
        ],
        "when_to_call_ems": "All snakebites — antivenom is only definitive treatment.",
        "protocol_reference": "WHO Snakebite Envenomation Guidelines 2019; WHO NTD Snakebite Action Plan 2021",
        "keywords": ["snake_bite", "snakebite", "envenomation", "venom", "antivenom"],
    },
    {
        "condition": "obstetric_emergency",
        "display_name": "Obstetric Emergency",
        "priority": "immediate",
        "triage_color": "red",
        "steps": [
            "Call EMS with obstetric capability immediately.",
            "Position mother on her left side to relieve aortocaval compression.",
            "Assess: gestational age, contractions, bleeding, and baby's position.",
            "For postpartum haemorrhage: fundal massage; express clots; assist with oxytocin if available.",
            "For cord prolapse: position mother in knee-chest position; cover cord with warm moist cloth.",
            "For eclamptic seizure: protect from injury, left lateral position, call for magnesium sulphate.",
            "For imminent delivery: time contractions; prepare clean surface; do NOT delay delivery.",
            "Monitor maternal vital signs and foetal heart rate continuously.",
        ],
        "visual_signs": [
            "Active vaginal bleeding (placental abruption, placenta praevia, PPH)",
            "Visible umbilical cord at introitus (cord prolapse)",
            "Facial oedema and severe headache with hypertension (pre-eclampsia)",
            "Foetal presenting part visible (imminent delivery)",
        ],
        "do_not_do": [
            "Do NOT delay transport for obstetric emergencies.",
            "Do NOT push cord back — keep moist and cover only.",
            "Do NOT withhold oxygen during obstetric emergencies.",
        ],
        "when_to_call_ems": "All obstetric emergencies — immediately.",
        "protocol_reference": "WHO ETAT 2016 Obstetric Emergencies; WHO Recommendations for PPH 2012",
        "keywords": ["obstetric_emergency", "postpartum_haemorrhage", "eclampsia", "cord_prolapse", "labour", "childbirth"],
    },
]

# ── Seeding logic ─────────────────────────────────────────────────────────────

async def seed() -> None:
    from google.cloud import firestore  # type: ignore

    project = os.environ.get("GOOGLE_CLOUD_PROJECT")
    db = firestore.AsyncClient(project=project) if project else firestore.AsyncClient()

    logger.info("Seeding %d WHO protocols into Firestore…", len(PROTOCOLS))

    for protocol in PROTOCOLS:
        condition = protocol["condition"]
        doc_ref = db.collection("who_protocols").document(condition)
        await doc_ref.set(protocol)
        logger.info("  ✓ %s", condition)

    logger.info("Seeding complete.")


if __name__ == "__main__":
    asyncio.run(seed())
